# Generated by Django 4.2.3 on 2025-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='variations_image'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
