# Generated by Django 4.2.3 on 2023-07-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time Record Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Time Record Updated')),
                ('created_by', models.EmailField(max_length=254)),
                ('updated_by', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='If Record Is Active')),
                ('fname', models.CharField(db_index=True, max_length=200)),
                ('lname', models.CharField(db_index=True, max_length=200)),
                ('title', models.CharField(default='', max_length=200, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=200)),
                ('office', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='staff_images')),
                ('qrcode_image', models.ImageField(blank=True, upload_to='qrcode_images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
