# Generated by Django 4.2.3 on 2023-08-02 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time Record Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Time Record Updated"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="If Record Is Active"
                    ),
                ),
                (
                    "fname",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="First Name"
                    ),
                ),
                (
                    "lname",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Last Name"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("phone", models.CharField(db_index=True, max_length=200)),
                ("office", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "company_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Company Website"
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "slug",
                    models.SlugField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="WebLink Slug",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="staff_images",
                        verbose_name="Profile Image",
                    ),
                ),
                (
                    "qrcode_img_vcard",
                    models.ImageField(
                        blank=True,
                        upload_to="vcard-qrcodes",
                        verbose_name="Contact Card QRcode",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
