# Generated by Django 4.2.3 on 2023-07-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_staff_created_by_alter_staff_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='fname',
            field=models.CharField(db_index=True, max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, upload_to='staff_images', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lname',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='office',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qrcode_image',
            field=models.ImageField(blank=True, upload_to='qrcode_images', verbose_name='Contact Card QRcode'),
        ),
    ]
