# Generated by Django 4.2.3 on 2023-08-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_rename_fname_staff_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='birthday',
            field=models.DateField(db_index=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='staff',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='Join Date'),
        ),
        migrations.AddField(
            model_name='staff',
            name='nick_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Nick Name'),
        ),
        migrations.AddField(
            model_name='staff',
            name='occupation',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='staff',
            name='team',
            field=models.CharField(choices=[('Management', 'Management'), ('Sales Team', 'Sales Team')], db_index=True, default='Sales Team', max_length=50),
        ),
    ]
