# Generated by Django 4.2.3 on 2023-08-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_staff_area_staff_birthday_staff_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
