# Generated by Django 4.2.3 on 2023-07-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_staff_fname_alter_staff_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='qrcode_image',
        ),
        migrations.AddField(
            model_name='staff',
            name='qrcode_img_vcard',
            field=models.ImageField(blank=True, upload_to='vcard-qrcodes', verbose_name='Contact Card QRcode'),
        ),
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='WebLink Slug'),
        ),
    ]
