# Generated by Django 4.2.3 on 2023-08-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_alter_staff_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
    ]
