# Generated by Django 4.2.3 on 2023-08-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_alter_staff_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.AddField(
            model_name='staff',
            name='full_name',
            field=models.CharField(db_index=True, default='not given', max_length=200, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
