# Generated by Django 4.2.3 on 2025-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='url_href',
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='banner title', max_length=50),
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
