# Generated by Django 4.2.3 on 2025-01-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_remove_banner_url_href_banner_title_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='index',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
