# Generated by Django 4.2.3 on 2025-01-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_sociallink_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='isShop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin-in', 'Linkedin'), ('x-twitter', 'X twitter'), ('tiktok', 'Tiktok'), ('shopee', 'Shopee'), ('lazada', 'Lazada')], max_length=50),
        ),
    ]
