# Generated by Django 4.2.3 on 2025-01-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_banner_isshop_alter_sociallink_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='banner',
            name='isShop',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='is_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='JournalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journals/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='banner.journal')),
            ],
        ),
    ]
