# Generated by Django 4.2.3 on 2025-01-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_journal_remove_banner_isshop_sociallink_is_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('youtube', 'Youtube'), ('linkedin-in', 'Linkedin'), ('x-twitter', 'X twitter'), ('tiktok', 'Tiktok'), ('shopee', 'Shopee'), ('lazada', 'Lazada')], max_length=50),
        ),
    ]
