# Generated by Django 4.2.3 on 2025-02-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_alter_sociallink_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='videoLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
